// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXb6s-I9A1evYyctnuiaFZMRfGGHTWZUQ',
    appId: '1:514395572702:web:ab1fb70580fbb59938b54f',
    messagingSenderId: '514395572702',
    projectId: 'ecommerce-1ad02',
    authDomain: 'ecommerce-1ad02.firebaseapp.com',
    databaseURL: 'https://ecommerce-1ad02-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ecommerce-1ad02.appspot.com',
    measurementId: 'G-TEKRJ3W1FR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ2AS-IyfSP_oPD2mR-T5KSQPtiN-ZD2E',
    appId: '1:514395572702:android:00022ec26be4dc5b38b54f',
    messagingSenderId: '514395572702',
    projectId: 'ecommerce-1ad02',
    databaseURL: 'https://ecommerce-1ad02-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ecommerce-1ad02.appspot.com',
  );
}
